### ISSUE TITLE
Support for adding a control sequence?

### ISSUE THREAD

**Issue by jsimons8** [JuliaGNSS/KalmanFilters.jl#15]
Hello, I am wondering if there would be support to add a control sequence $u_t$ in the model like so:

$x_t = F x_{t-1} + G u_t + v_t$
$x_t = H x_{t} + A u_t + w_t$

see also [here](https://en.wikipedia.org/wiki/Kalman_filter#Underlying_dynamic_system_model), where a control vector sequence is added to the model.

The $A$ matrix is less important but the $G$ matrix is important.

Do you know if this is supported in KalmanFilters?

Thank you!

**Comment by jsimons8** [comment]
Hi @zsoerenm thank you for responding to my query. However, `x` must be extracted manually first, right, from `get_state`? I believe you had an earlier version of your answer that did something like this.

Does the same idea work with `measurement_update`, too? Moreover, in the updating equations `G` appears, as well, but I am guessing this is then accommodated automatically by the new state?

**Comment by zsoerenm** [comment]
Yes, it is the same as:
```
tu = time_update(get_state(mu) + G * u, get_covariance(mu), F, Q)
```
where `mu` is the last measurement update.

> Moreover, in the updating equations G appears, as well

It should only appear in the time update.

I have never seen a control vector for the measurement update, but if you equation above is correct, you can use the same trick as for the time update.
