### ISSUE TITLE
calc_innovation! fails with broadcast errors for mxn H matrix 

### ISSUE THREAD

**Issue by zagglez** [JuliaGNSS/KalmanFilters.jl#6]
Following: https://www.kalmanfilter.net/multiExamples.html - 6 states, 2 measurements.

H = [ 1  0  0  0  0  0
         0  0  0  1  0  0 ]   
ie, a 2x6 matrix.

OK so with the normal linear KF, everything works fine.

However, the inplace version of calc_innovation, ie calc_innovation! errors with:
DimensionMismatch("cannot broadcast array to have fewer non-singleton dimensions")

**Comment by zsoerenm** [comment]
Could you provide a minimum working example?

**Comment by zsoerenm** [comment]
I have made some changes. So this might work now.
I will close this. Feel free to re-open the issue, if it doesn't work for you.
